AreaDataList=[
    "01 Ajmer",
    "Vaishali Nagar",
    "Kundan Nagar",
    "Pahar Ganj",
    "Chandra Vardai Nagar",
    "Subhash Nagar",
    "Civil Lines",
    "Dhola Bhata Colony",
    "Dayanand Colony",
    "Pragati Nagar",
    "Makadwali",
    "Railway Quarters",
    "Gulab Bari",
    "Gandhi Nagar",
    "Indra Colony",
    "Tilak Nagar",
    "Parbatpura",
    "Ghooghra",
    "Gegal",
    "Madanganj",
    "Parbatpura",
    "Topdara",
    "Pal Bhichala",
    "Dargah Bazar",
    "Makhupura",
    "Arya Nagar",
    "Ganj",
    "Mahanton Ka Mohalla",
    "Adarsh Nagar",
    "Naya Bazar",
    "Kala Bagh",
    "Fatehlal Nagar",
    "Onkar Nagar",
    "Indira Colony",
    "Kaisar Ganj",
    "Aana sagar",
    "Mitra Niwas Colony",
    "Prithviraj Nagar",
    "Patel Nagar",
    "Prithviraj Nagar",
    "Mahesh Nagar",
    "Teli Mohalla",
    "Madanganj",
    "Basant Vihar",
    "Ganahera",
    "Pushkar",
    "Deshwali Mohalla",
    "Agrasen Nagar",
    "Parao",
    "R K Colony",
    "Vivek Vihar Colony",
    "Dumada",
    "New Kesari Colony",
    "Bohra Colony",
    "Bhat Mohalla",
    "Hathi Bhata",
    "Civil Lines",
    "Kotra",
    "Panchsheel Nagar",
    "Bhajan Ganj",
    "Daurai",
]

AreaDataList = sorted(AreaDataList)
