AreaDataList=[
    "Ajmer",
    "Vaishali Nagar",
    "Kundan Nagar",
    "Pahar Ganj",
    "Chandra Vardai Nagar",
    "Subhash Nagar",
    "Civil Lines",
    "Ajmer District",
    "Dhola Bhata Colony",
    "Adarsh Nagar",
    "Dayanand Colony",
    "Pragati Nagar",
    "Makadwali",
    "Railway Quarters",
    "Gulab Bari",
    "Gandhi Nagar",
    "Indra Colony",
    "Tilak Nagar",
    "Parbatpura",
    "Ajay Nagar" ,
    "Ghooghra",
    "Gegal",
    "Madanganj",
    "Parbatpura",
    "Topdara",
    "Bhajan Ganj",
    "Pal Bhichala",
    "Civil Lines",
    "Dargah Bazar",
    "Makhupura",
    "Arya Nagar",
    "Ganj",
    "Mahanton Ka Mohalla",
    "Adarsh Nagar",
    "Naya Bazar",
    "Kala Bagh",
    "Fatehlal Nagar",
    "Onkar Nagar",
    "Basant Vihar",
    "Vivek Vihar Colony",
    "Indira Colony",
    "Kaisar Ganj",
    "Aana sagar",
    "Mitra Niwas Colony",
    "Prithviraj Nagar",
    "Patel Nagar",
    "Prithviraj Nagar",
    "Mahesh Nagar",
    "Adarash Colony",
    "Teli Mohalla",
    "Madanganj",
    "Basant Vihar",
    "Ganahera",
    "Pushkar",
    "Deshwali Mohalla",
    "Agrasen Nagar",
    "Parao",
    "R K Colony",
    "Vivek Vihar Colony",
    "Dumada",
    "New Kesari Colony",
    "Bohra Colony",
    "Bhat Mohalla",
    "Hathi Bhata",
    "Civil Lines",
    "Kotra",
    "Panchsheel Nagar",
    "Bhajan Ganj",
    "Daurai",
    "Dayanand Colony",
]

AreaDataList = sorted(AreaDataList)
